myapp/config/routes.rb
Myapp::Application.routes.draw do
  get "search/show"

  get "search/reservation"

  resources :apps

   root :to => 'search#reservation'

end

myapp/app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :email, :name
end

myapp/app/models/booking.rb
class Booking < ActiveRecord::Base
set_primary_key :booking_ref
  attr_accessible :booking_id, :end_date, :no_of_guest, :room_id, :start_date
  belongs_to :Room
  
  def self.search(search1, search2, search3)
    if search1
	 Booking.where("start_date >=  ? and end_date <= ?", search1, search2).all
	 
    else
     find(:all)
    end
end
end

myapp/app/models/host.rb
class Host < ActiveRecord::Base
  attr_accessible :address, :host_id, :name
  set_primary_key :host_id
  has_many :Rooms
end

myapp/app/models/room.rb
class Room < ActiveRecord::Base
  set_primary_key :room_id
  attr_accessible :capacity, :host_id, :room_id
  
  belongs_to :Host
  has_many :Bookings
  
  def self.search(search1, search2, search3)
     
    if search3
     
	 Room.select(" hosts.host_id,hosts.name,hosts.address,rooms.room_id, rooms.capacity, bookings.no_of_guest, rooms.capacity-bookings.no_of_guest as available").
     joins("LEFT JOIN bookings ON rooms.room_id = bookings.room_id ", :Host).
     where (["bookings.start_date >= :sdate and bookings.end_date <= :edate", :sdate => search1, :edate => search2])
	 
	 
	 
	 	 
    else
    
    end
end
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

myapp/app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

myapp/app/controllers/search_controller.rb
class SearchController < ApplicationController
    
  def reservation
  
  end
  
  def show
  date = params["s_date"]
  date1 = params["e_date"]
  sdate=Date.new(date["s_date(1i)"].to_i,date["s_date(2i)"].to_i,date["s_date(3i)"].to_i)
  start_date=sdate.to_date
  edate=Date.new(date1["e_date(1i)"].to_i,date1["e_date(2i)"].to_i,date1["e_date(3i)"].to_i)
  end_date=edate.to_date
  cap= params["capacity"]
  @date1=start_date
  @date2=end_date
  @cap= cap
  
  @books = Room.search(start_date,end_date,cap)
  @books = @books.paginate(page: params[:page], :per_page => 5)
  
  
  
  end
  
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/apps_helper.rb
module AppsHelper
end

myapp/app/helpers/books_helper.rb
module BooksHelper
end

myapp/app/helpers/hots_helper.rb
module HotsHelper
end

myapp/app/helpers/qas_helper.rb
module QasHelper
end

myapp/app/helpers/room1s_helper.rb
module Room1sHelper
end

myapp/app/helpers/search_helper.rb
module SearchHelper
end

myapp/app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myapp/app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

myapp/app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= app.email %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

myapp/app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

myapp/app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Email:</b>
  <%= @app.email %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

myapp/app/views/search/_form.html.erb
<%= form_tag({:controller => 'search', :action => 'show'}, {:method => 'get'}) do %>
Date From:<%= date_select(:s_date, "s_date", :order => [:day, :month, :year]) %><br /><br />
Date To       :<%= date_select(:e_date, "e_date", :order => [:day, :month, :year]) %><br /><br />
No. of Guest  :<%= text_field_tag :capacity, params[:capacity] %><br /><br /><br /><br /><br />
<%= submit_tag("   Go   ", :style => "font-size: 20px;") %>
<% end %>
<br />

myapp/app/views/search/reservation.html.erb
<h1> HomeStay Reservation System</h1></br>
</br><%= render 'form' %>

myapp/app/views/search/show.html.erb
<h1>Reservation Results</h1>
<p></p>
<div id="Data"> 
 

   Search results between <%= @date1 %> and <%= @date2 %> for <%= @cap %> guest </br></br></br>
<% a = "" %>
<% @books.each do|bk| %>
  <% if a != bk.host_id %>
  <%= bk.host_id %></br>
  <%= bk.name %></br>
  <%= bk.address %></br>
  <%= bk.room_id %> is available (<%= bk.no_of_guest%> booked, <%= bk.available %> free out of <%= bk.capacity%> total)
  <% a = bk.host_id%>
  <% else %>
  <%= bk.room_id %> is available (<%= bk.no_of_guest%> booked, <%= bk.available %> free out of <%= bk.capacity%> total)</br>
  <% end %>
  </br>
  </br>
  </div>
  <% end %>
  <%= will_paginate @books %>
  <%= link_to "Back", :controller => :search, :action => :reservation %>
  